[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
matplotlib = "*"
numpy = "*"
pandas = "*"

[tool.poetry.group.dev.dependencies]
matplotlib = "*"
numpy = "*"
pandas = "*"
ruff = "*"
